<?php

return [
    'activation_fees' => [
        'earner' => env('EARNER_ACTIVATION_FEE', 1500),
        'task_creator' => 0,
        'freelancer' => 0,
        'digital_seller' => 0,
        'growth_seller' => 0,
        'buyer' => 0,
    ],

     'features' => [
         'task_creation' => [
             'label' => 'Task Creation',
             'allowed_roles' => ['task_creator', 'buyer', 'earner', 'freelancer', 'digital_seller', 'growth_seller', 'admin'],
             'unlockable_roles' => ['task_creator', 'buyer', 'freelancer', 'digital_seller', 'growth_seller'],
             'always_enabled_for_roles' => ['task_creator', 'admin'],
              'unlock_route' => 'onboarding.feature.unlock.page',
             'unlock_message' => 'Unlock task creation to start hiring workers and creating jobs on the marketplace.',
             'unlock_action' => 'Unlock Feature',
             'context_message' => 'Create and manage tasks with your account',
             'periods' => [
                 'initial' => ['cost' => 1000, 'months' => 3],
                 'monthly' => ['cost' => 500, 'months' => 1],
                 'quarterly' => ['cost' => 1000, 'months' => 3],
             ],
         ],
         'available_tasks' => [
             'label' => 'Available Tasks',
             'allowed_roles' => ['task_creator', 'earner', 'freelancer', 'digital_seller', 'growth_seller', 'buyer', 'admin'],
             'unlockable_roles' => [],
             'always_enabled_for_roles' => ['earner', 'admin'],
              'unlock_route' => 'onboarding.feature.unlock.page',
             'unlock_message' => 'Unlock task browsing to find work opportunities and earn money.',
             'unlock_action' => 'Unlock Feature',
             'context_message' => 'Browse available tasks to earn',
             'periods' => [
                 'initial' => ['cost' => 1000, 'months' => 3],
                 'monthly' => ['cost' => 500, 'months' => 1],
                 'quarterly' => ['cost' => 1000, 'months' => 3],
             ],
         ],
         'professional_services' => [
             'label' => 'Professional Services',
             'allowed_roles' => ['task_creator', 'earner', 'freelancer', 'digital_seller', 'growth_seller', 'buyer', 'admin'],
             'unlockable_roles' => ['task_creator', 'buyer'],
             'always_enabled_for_roles' => ['freelancer', 'admin'],
             'unlock_route' => 'onboarding.feature.unlock.page',
             'unlock_message' => 'Unlock professional services to hire freelancers or offer your services.',
             'unlock_action' => 'Unlock Feature',
             'context_message' => 'Access the professional services marketplace.',
             'periods' => [
                 'initial' => ['cost' => 1000, 'months' => 3],
                 'monthly' => ['cost' => 500, 'months' => 1],
                 'quarterly' => ['cost' => 1000, 'months' => 3],
             ],
         ],
         'growth_listings' => [
             'label' => 'Growth Marketplace',
             'allowed_roles' => ['task_creator', 'earner', 'freelancer', 'digital_seller', 'growth_seller', 'buyer', 'admin'],
             'unlockable_roles' => ['task_creator', 'buyer'],
             'always_enabled_for_roles' => ['growth_seller', 'admin'],
              'unlock_route' => 'onboarding.feature.unlock.page',
             'unlock_message' => 'Unlock growth marketplace to buy/sell leads and backlinks.',
             'unlock_action' => 'Unlock Feature',
             'context_message' => 'Access growth and marketing services.',
             'periods' => [
                 'initial' => ['cost' => 1000, 'months' => 3],
                 'monthly' => ['cost' => 500, 'months' => 1],
                 'quarterly' => ['cost' => 1000, 'months' => 3],
             ],
         ],
         'digital_products' => [
             'label' => 'Digital Products',
             'allowed_roles' => ['task_creator', 'earner', 'freelancer', 'digital_seller', 'growth_seller', 'buyer', 'admin'],
             'unlockable_roles' => ['task_creator', 'buyer'],
             'always_enabled_for_roles' => ['digital_seller', 'admin'],
              'unlock_route' => 'onboarding.feature.unlock.page',
             'unlock_message' => 'Unlock digital products marketplace to buy/sell templates and plugins.',
             'unlock_action' => 'Unlock Feature',
             'context_message' => 'Access the digital product marketplace.',
             'periods' => [
                 'initial' => ['cost' => 1000, 'months' => 3],
                 'monthly' => ['cost' => 500, 'months' => 1],
                 'quarterly' => ['cost' => 1000, 'months' => 3],
             ],
         ],
         'freelance_marketplace' => [
             'label' => 'Freelance Marketplace',
             'allowed_roles' => ['freelancer', 'admin'],
             'unlockable_roles' => [],
             'always_enabled_for_roles' => ['freelancer', 'admin'],
             'unlock_route' => 'unlock-access',
             'unlock_message' => 'Switch to Freelancer account to offer professional services.',
             'unlock_action' => 'Become Freelancer',
             'context_message' => 'Professional services marketplace for freelancers.',
             'periods' => [],
         ],
         'digital_selling' => [
             'label' => 'Digital Seller',
             'allowed_roles' => ['digital_seller', 'admin'],
             'unlockable_roles' => [],
             'always_enabled_for_roles' => ['digital_seller', 'admin'],
             'unlock_route' => 'unlock-access',
             'unlock_message' => 'Switch to Digital Seller account to sell digital products.',
             'unlock_action' => 'Become Digital Seller',
             'context_message' => 'Sell digital products and templates.',
             'periods' => [],
         ],
         'growth_selling' => [
             'label' => 'Growth Seller',
             'allowed_roles' => ['growth_seller', 'admin'],
             'unlockable_roles' => [],
             'always_enabled_for_roles' => ['growth_seller', 'admin'],
             'unlock_route' => 'unlock-access',
             'unlock_message' => 'Switch to Growth Seller account to sell leads and backlinks.',
             'unlock_action' => 'Become Growth Seller',
             'context_message' => 'Sell growth services and marketing leads.',
             'periods' => [],
         ],
     ],

    'feature_aliases' => [
        'growth_marketplace' => 'growth_listings',
    ],
];
